# Generated by Django 5.1.3 on 2024-11-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_classrequest_preferred_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrequest',
            name='preferred_time',
        ),
        migrations.RemoveField(
            model_name='classrequest',
            name='selected_item',
        ),
        migrations.AlterField(
            model_name='classrequest',
            name='category',
            field=models.CharField(choices=[('Math', 'Mathematics'), ('Science', 'Science')], max_length=50),
        ),
    ]
