# Generated by Django 5.1.3 on 2024-11-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_classrequest_preferred_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerapplication',
            name='zoom_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
