# Generated by Django 5.1.3 on 2024-11-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_book_earnings_delete_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrequest',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
