# Generated by Django 5.1.3 on 2024-11-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_classrequest_responded'),
    ]

    operations = [
        migrations.CreateModel(
            name='display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=255)),
                ('p', models.CharField(max_length=250)),
                ('line', models.CharField(max_length=250)),
            ],
        ),
    ]
