# Generated by Django 5.1.3 on 2024-11-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_display'),
    ]

    operations = [
        migrations.DeleteModel(
            name='display',
        ),
    ]
