# Generated by Django 5.1.3 on 2024-11-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_delete_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerapplication',
            name='is_lecturer',
            field=models.BooleanField(default=False),
        ),
    ]
